import Dexie, { type Table } from 'dexie';

// ---------- Types ----------

export interface MenuCacheEntry {
  id: string;
  categoryId: string;
  nameFr: string;
  nameAr?: string;
  priceCents: number;
  available: boolean;
  sortOrder: number;
  cachedAt: number; // epoch ms
}

export interface LocalOrder {
  id: string;          // UUID generated by client
  localNumber: number; // temporary display number, replaced by server number at sync
  tenantId: string;
  status: string;
  items: unknown[];
  totalCents: number;
  createdAt: number;
}

export interface SyncQueueItem {
  id?: number;         // auto-increment
  entityType: 'order' | 'payment' | 'orderItem';
  entityId: string;
  payload: unknown;
  status: 'pending' | 'synced' | 'failed';
  retries: number;
  createdAt: number;
}

// ---------- DB ----------

class PosDatabase extends Dexie {
  menuCache!: Table<MenuCacheEntry, string>;
  orders!: Table<LocalOrder, string>;
  syncQueue!: Table<SyncQueueItem, number>;

  constructor() {
    super('restaurant_pos');
    this.version(1).stores({
      menuCache: 'id, categoryId, available',
      orders:    'id, status, createdAt',
      syncQueue: '++id, status, entityType, entityId',
    });
  }
}

export const db = new PosDatabase();
